# Generated by Django 5.0.14 on 2026-02-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='director_name',
            field=models.CharField(blank=True, help_text='Masalan: B.Xolbutayev', max_length=255, null=True, verbose_name='Direktor ism-sharifi'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.CharField(blank=True, help_text='Masalan: Angor tumani', max_length=255, null=True, verbose_name='Tuman/Shahar nomi'),
        ),
    ]
