# Generated by Django 5.0.14 on 2026-02-20 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_director_name_organization_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Kafedra', 'verbose_name_plural': 'Kafedralar'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlar'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Metod birlashma', 'verbose_name_plural': 'Metod birlashmalar'},
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Mudiri'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.organization', verbose_name='Tashkilot'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='organization.department', verbose_name='Kafedra'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_units', to=settings.AUTH_USER_MODEL, verbose_name='Rahbari'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
    ]
