# Generated by Django 5.0.14 on 2026-02-16 04:32

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='passport_number',
            field=core.fields.EncryptedField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='salary',
            field=core.fields.EncryptedField(blank=True, help_text='Monthly salary in UZS', null=True),
        ),
    ]
