# Generated by Django 5.0.14 on 2026-02-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employeeprofile_passport_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
