# Generated by Django 5.0.14 on 2026-02-16 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employeeprofile_address_employeeprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Masalan: IELTS 7.5, CEFR C1', max_length=255, verbose_name='Sertifikat nomi')),
                ('issuer', models.CharField(blank=True, help_text='Masalan: British Council', max_length=255, verbose_name='Beruvchi tashkilot')),
                ('date_issued', models.DateField(verbose_name='Berilgan sana')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Sertifikat fayli (PDF/JPG)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-date_issued'],
            },
        ),
    ]
