# Generated by Django 5.0.14 on 2026-02-20 04:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Yil (Masalan: 2026)', unique=True)),
                ('last_number', models.PositiveIntegerField(default=0, help_text="Oxirgi berilgan ma'lumotnoma raqami")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
