# Generated by Django 5.0.14 on 2026-02-20 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_certificatesequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatesequence',
            options={'verbose_name': "Ma'lumotnoma Tartib Raqami", 'verbose_name_plural': "Ma'lumotnoma Tartib Raqamlari"},
        ),
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'verbose_name': 'Xodim Profili', 'verbose_name_plural': 'Xodimlar Profillari'},
        ),
        migrations.AlterModelOptions(
            name='kpiindicator',
            options={'verbose_name': 'KPI Indikatori', 'verbose_name_plural': 'KPI Indikatorlari'},
        ),
        migrations.AlterModelOptions(
            name='kpirecord',
            options={'verbose_name': 'KPI Yozuvi (Natijasi)', 'verbose_name_plural': 'KPI Yozuvlari (Natijalari)'},
        ),
        migrations.AlterField(
            model_name='certificatesequence',
            name='last_number',
            field=models.PositiveIntegerField(default=0, help_text="Oxirgi berilgan ma'lumotnoma raqami", verbose_name='Oxirgi raqam'),
        ),
        migrations.AlterField(
            model_name='certificatesequence',
            name='year',
            field=models.IntegerField(help_text='Yil (Masalan: 2026)', unique=True, verbose_name='Yil'),
        ),
        migrations.AlterField(
            model_name='kpiindicator',
            name='criteria',
            field=models.TextField(help_text='Ushbu KPI ga erishish qoidalari', verbose_name='Mezonlar'),
        ),
        migrations.AlterField(
            model_name='kpiindicator',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='kpiindicator',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='kpiindicator',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Ushbu indikator uchun beriladigan ball', max_digits=5, verbose_name='Vazni'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='date_achieved',
            field=models.DateField(verbose_name='Erishilgan sana'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='hr.kpiindicator', verbose_name='Indikator'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='kpi_proofs/', verbose_name='Isbotlovchi hujjat'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='score_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Olingan ball'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_records', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan'),
        ),
    ]
