# Generated by Django 5.0.14 on 2026-03-05 15:56

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_certificatesequence_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/', verbose_name='Qiyofacha (Avatar)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Tarjimayi hol (Bio)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='certificates',
            field=models.JSONField(blank=True, default=list, verbose_name='Sertifikatlar (JSON)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employment_contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Shartnoma tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='passport_number',
            field=core.fields.EncryptedField(blank=True, null=True, verbose_name='Pasport raqami/JShSHIR'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='qualification_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Malaka toifasi / Aniq vazifasi'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='salary',
            field=core.fields.EncryptedField(blank=True, help_text='Oylik maosh (UZS)', null=True, verbose_name='Oylik maosh'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Boshlash sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('certificate_file', models.FileField(upload_to='sick_leaves/', verbose_name='Kasallik varaqasi (fayl)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('hr_note', models.TextField(blank=True, verbose_name='HR izohi')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqt")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sick_leaves', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqqan HR")),
            ],
            options={
                'verbose_name': 'Kasallik Varaqasi',
                'verbose_name_plural': 'Kasallik Varaqalari',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
