# Generated by Django 6.0.6 on 2026-06-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_employeeprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='certificates/', verbose_name='Sertifikat fayli (PDF/JPG)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', max_length=500, upload_to='avatars/', verbose_name='Qiyofacha (Avatar)'),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='proof_document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='kpi_proofs/', verbose_name='Isbotlovchi hujjat'),
        ),
    ]
