# Generated by Django 5.0.14 on 2026-02-16 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Buyruq mavzusi')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Buyruq raqami')),
                ('file', models.FileField(upload_to='orders/', verbose_name='Buyruq fayli (PDF/Word)')),
                ('date_signed', models.DateField(verbose_name='Imzolangan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buyruq',
                'verbose_name_plural': 'Buyruqlar',
                'ordering': ['-date_signed'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Hisobot nomi')),
                ('report_type', models.CharField(choices=[('QUARTERLY', 'Choraklik Hisobot'), ('ANNUAL', 'Yillik Hisobot'), ('OTHER', 'Boshqa')], default='QUARTERLY', max_length=20)),
                ('file', models.FileField(upload_to='reports/', verbose_name='Hisobot fayli')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Topshirildi (Submitted)'), ('APPROVED', 'Tasdiqlandi (Approved)'), ('REJECTED', 'Rad etildi (Rejected)')], default='SUBMITTED', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Admin izohi (Rad etish sababi)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hisobot',
                'verbose_name_plural': 'Hisobotlar',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
