# Generated by Django 6.0.6 on 2026-06-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(max_length=500, upload_to='orders/', verbose_name='Buyruq fayli (PDF/Word)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(max_length=500, upload_to='reports/', verbose_name='Hisobot fayli'),
        ),
    ]
