# Generated by Django 6.0.6 on 2026-06-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to='task_attachments/'),
        ),
    ]
